#!/usr/bin/env bash
# scripts/scaffold.sh
#
# Creates the frozen folder structure for the Code Comprehension project
# (see docs/FOLDER_STRUCTURE.md). Safe to re-run: it NEVER overwrites a file
# that already exists, it only creates what is missing.
#
# Usage (from anywhere inside the repo, needs bash: Git Bash / WSL / macOS / Linux):
#   bash scripts/scaffold.sh
#
# Optional: set the GitHub handles used in .github/CODEOWNERS
#   M1_GH=@alice M2_GH=@bob M3_GH=@carol M4_GH=@dave bash scripts/scaffold.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
M1="${M1_GH:-@REPLACE-M1}"
M2="${M2_GH:-@REPLACE-M2}"
M3="${M3_GH:-@REPLACE-M3}"
M4="${M4_GH:-@REPLACE-M4}"

CREATED=0
SKIPPED=0

# ---------------------------------------------------------------- helpers

# wf <relative-path>   write stdin to the file unless it already exists
wf() {
  local target="$ROOT/$1"
  mkdir -p "$(dirname "$target")"
  if [[ -e "$target" ]]; then
    SKIPPED=$((SKIPPED + 1))
    cat > /dev/null
    return 0
  fi
  cat > "$target"
  CREATED=$((CREATED + 1))
}

# keep <relative-dir>  make an otherwise empty folder trackable by git
keep() { wf "$1/.gitkeep" < /dev/null; }

# py <path> <owner> <purpose>   python placeholder with a header docstring
py() {
  wf "$1" <<EOF
"""$3

Owner: $2
Placeholder created by scripts/scaffold.sh. Replace with real code.
"""
EOF
}

# sh_stub <path> <owner> <purpose>   executable shell placeholder
sh_stub() {
  wf "$1" <<EOF
#!/usr/bin/env bash
# Owner: $2. Placeholder created by scripts/scaffold.sh.
# Purpose: $3
echo "TODO: implement $1" >&2
exit 1
EOF
  chmod +x "$ROOT/$1"
}

# page <path> <label>      Next.js page placeholder
page() {
  wf "$1" <<EOF
// Owner: Member 4. Placeholder created by scripts/scaffold.sh.
export default function Page() {
  return <div>TODO: $2</div>;
}
EOF
}

# layout <path>            Next.js layout placeholder
layout() {
  wf "$1" <<EOF
// Owner: Member 4. Placeholder created by scripts/scaffold.sh.
// TODO: role guard for this portal (UX only, the API enforces real access).
export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
EOF
}

# comp <path> <Name>       React component placeholder
comp() {
  wf "$1" <<EOF
// Owner: Member 4. Placeholder created by scripts/scaffold.sh.
export function $2() {
  return null;
}
EOF
}

# ts <path> <purpose>      TypeScript module placeholder
ts() {
  wf "$1" <<EOF
// Owner: Member 4. Placeholder created by scripts/scaffold.sh.
// $2
export {};
EOF
}

# txt <path> <owner> <purpose>   plain text placeholder (prompt templates)
txt() {
  wf "$1" <<EOF
# Owner: $2. Placeholder created by scripts/scaffold.sh.
# Purpose: $3
EOF
}

echo "Scaffolding into: $ROOT"

# ---------------------------------------------------------------- root files

wf README.md <<'EOF'
# Code Comprehension & Verification System

Hackathon project (Track A). Full team documentation is in `docs/`. Start with `docs/README.md`.

Quick start: see `docs/SETUP_AND_ENV.md`. Folder rules: see `docs/FOLDER_STRUCTURE.md`.
EOF

wf .gitignore <<'EOF'
# secrets (never commit)
.env
.env.local
.env.*.local

# python
.venv/
__pycache__/
*.pyc
.pytest_cache/
.ruff_cache/

# node
node_modules/
.next/
out/

# local data and backups
demo/backup/*
!demo/backup/.gitkeep
*.dump
*.sql

# os / editor
.DS_Store
.idea/
.vscode/
EOF

wf .editorconfig <<'EOF'
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2

[*.py]
indent_size = 4

[*.md]
trim_trailing_whitespace = false
EOF

wf .github/CODEOWNERS <<EOF
# CODEOWNERS (generated by scripts/scaffold.sh)
# Replace the @REPLACE-Mx placeholders with real GitHub usernames.
# Shared folders list all four members: approval from one of them is enough.

/backend/app/                      $M1
/backend/alembic/                  $M1
/backend/alembic.ini               $M1
/scripts/                          $M1
/backend/tests/api/                $M1

/backend/analysis/                 $M2
/backend/tests/analysis/           $M2
/backend/tests/fixtures/programs/  $M2

/backend/ai/                       $M3
/backend/tests/ai/                 $M3
/backend/tests/fixtures/answers/   $M3

/frontend/                         $M4
/demo/                             $M4

/backend/common/                   $M1 $M2 $M3 $M4
/contracts/                        $M1 $M2 $M3 $M4
/docs/                             $M1 $M2 $M3 $M4
/.github/                          $M1 $M2 $M3 $M4
EOF

wf .github/pull_request_template.md <<'EOF'
## What changed
<!-- One or two sentences -->

## Area (owner)
- [ ] backend/app (M1)  - [ ] backend/analysis (M2)  - [ ] backend/ai (M3)  - [ ] frontend (M4)
- [ ] backend/common, contracts or docs (shared, needs another member's review)

## Checklist
- [ ] Tests added or updated, and they pass
- [ ] No secrets, `.env` files or real student data committed
- [ ] If an API or schema changed: `contracts/` and the generated frontend types were updated
- [ ] If the folder structure changed: the team agreed first (see docs/FOLDER_STRUCTURE.md)

## Screenshots / notes
EOF

keep docs

# ---------------------------------------------------------------- contracts

wf contracts/README.md <<'EOF'
# contracts/

Language-neutral examples of the shared data shapes, reviewed by all four members.
The Pydantic models in `backend/common/` are the source of truth; these JSON files
are examples for fixtures, mocks (frontend MSW) and tests.

`openapi.snapshot.json` is generated from the running backend and committed so
the frontend team can see API changes in pull requests. Do not edit it by hand.
EOF

wf contracts/examples/code_facts.example.json <<'EOF'
{
  "language": "python",
  "code_hash": "sha256:example",
  "line_count": 20,
  "functions": [
    {
      "name": "binary_search",
      "start_line": 3,
      "end_line": 18,
      "params": ["arr", "target"],
      "is_recursive": false,
      "cyclomatic_complexity": 4,
      "max_loop_depth": 1,
      "calls": ["len"]
    }
  ],
  "loops": [
    { "kind": "while", "start_line": 7, "end_line": 16, "depth": 1, "function": "binary_search" }
  ],
  "data_structures": ["list"],
  "imports": [],
  "edge_case_inputs": [
    { "function": "binary_search", "args": [[], 5], "label": "empty list" },
    { "function": "binary_search", "args": [[1], 1], "label": "single element" }
  ],
  "warnings": []
}
EOF

wf contracts/examples/question_public.example.json <<'EOF'
{
  "id": "00000000-0000-0000-0000-000000000001",
  "order_idx": 1,
  "type": "trace_output",
  "prompt": "What does binary_search([1, 3, 5, 7], 5) return?",
  "line_refs": [3, 18],
  "answer_format": "short_text",
  "options": null,
  "max_score": 10
}
EOF

wf contracts/examples/question_private.example.json <<'EOF'
{
  "id": "00000000-0000-0000-0000-000000000002",
  "type": "design_decision",
  "prompt": "Why did you use a while loop instead of recursion here?",
  "line_refs": [7],
  "answer_format": "free_text",
  "options": null,
  "max_score": 10,
  "answer_key": null,
  "rubric": {
    "expected_points": [
      "Avoids recursion depth limits and call overhead",
      "The loop condition shrinks the search range each iteration"
    ],
    "common_misconceptions": ["Says loops are always faster"],
    "scoring_guide": "Full marks for both points, half for one, zero for none or vague."
  },
  "explanation": "Shown to the teacher and in practice mode only.",
  "question_hash": "sha1:example"
}
EOF

wf contracts/examples/score.example.json <<'EOF'
{
  "question_id": "00000000-0000-0000-0000-000000000002",
  "score": 7.5,
  "max_score": 10,
  "evidence": "Student wrote that it halves the range each time, which matches rubric point 2.",
  "confidence": 0.82,
  "needs_review": false,
  "feedback": "Good on the range halving; also mention why not recursion."
}
EOF

wf contracts/examples/comprehension_result.example.json <<'EOF'
{
  "attempt_id": "00000000-0000-0000-0000-000000000003",
  "comprehension_index": 68.5,
  "sub_scores": { "trace": 80, "design": 55, "explanation": 60, "complexity": 70 },
  "flag_oral_followup": false,
  "needs_review_count": 1
}
EOF

wf contracts/openapi.snapshot.json <<'EOF'
{}
EOF

# ---------------------------------------------------------------- scripts (Member 1)

py scripts/seed.py "Member 1" "Idempotent seed: 2 teachers, 6 students, 2 groups, assignment, exam, 2 slots, sample submissions."
py scripts/reset_db.py "Member 1" "Drop and recreate the local dev database schema, then run migrations."
sh_stub scripts/dump_db.sh "Member 1" "Dump the local database to demo/backup/ (pg_dump)."
sh_stub scripts/restore_db.sh "Member 1" "Restore a dump from demo/backup/ (psql or pg_restore)."

# ---------------------------------------------------------------- demo (Members 2 + 4)

keep demo/submissions
wf demo/demo_script.md <<'EOF'
# Demo script

Copy the click path from docs/DEMO_AND_TESTING.md and keep it up to date here.
EOF
keep demo/backup

# ---------------------------------------------------------------- backend: config files

wf backend/requirements.txt <<'EOF'
fastapi
uvicorn[standard]
python-multipart
pydantic>=2
pydantic-settings
email-validator
sqlalchemy>=2
alembic
psycopg[binary]
pyjwt
argon2-cffi
apscheduler
anthropic
sse-starlette
tenacity
rapidfuzz
tree-sitter
tree-sitter-python
radon
pytest
httpx
ruff
EOF

wf backend/pyproject.toml <<'EOF'
[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
EOF

wf backend/.env.example <<'EOF'
DATABASE_URL=postgresql+psycopg://postgres:password@localhost:5432/codecomp
JWT_SECRET=change-me-to-a-long-random-string
JWT_EXPIRE_MINUTES=480
TEACHER_INVITE_CODE=choose-a-code
ANTHROPIC_API_KEY=sk-ant-...
MODEL_PRACTICE=claude-haiku-4-5-20251001
MODEL_EXAM=claude-sonnet-5-5
ALLOWED_ORIGINS=http://localhost:3000,https://your-app.vercel.app
COOKIE_SECURE=false
GENERATION_LEAD_MINUTES=30
CONFIDENCE_REVIEW_THRESHOLD=0.6
EOF

# ---------------------------------------------------------------- backend: alembic (Member 1)

wf backend/alembic.ini <<'EOF'
[alembic]
script_location = alembic
prepend_sys_path = .
# The database URL is read from the DATABASE_URL environment variable in alembic/env.py
sqlalchemy.url =

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
EOF

wf backend/alembic/env.py <<'EOF'
"""Alembic environment. Owner: Member 1.

Reads DATABASE_URL from the environment (or backend/.env if python-dotenv is installed).
Run alembic from the backend/ folder.
"""
import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

try:  # optional: load backend/.env
    from dotenv import load_dotenv

    load_dotenv()
except ImportError:
    pass

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Make autogenerate see the models once Member 1 has implemented them.
try:
    from app.db.base import Base
    import app.models  # noqa: F401

    target_metadata = Base.metadata
except ImportError as exc:
    print(f"[alembic env] models not importable yet, autogenerate disabled: {exc}", file=sys.stderr)
    target_metadata = None


def get_url() -> str:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is not set (see backend/.env.example)")
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
EOF

wf backend/alembic/script.py.mako <<'EOF'
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
EOF

keep backend/alembic/versions

# ---------------------------------------------------------------- backend/common (shared, joint ownership)

py backend/common/__init__.py "Shared (all members)" "Shared Pydantic models used by app, analysis and ai. Changes here need a review from another member."
py backend/common/code_facts.py "Shared (all members)" "CodeFacts, FunctionFacts, LoopFacts. Produced by analysis, consumed by ai and app. See docs/CONTRACTS.md."
py backend/common/question.py "Shared (all members)" "QuestionPublic, QuestionPrivate, PracticeQuestion and the type/answer-format enums. See docs/CONTRACTS.md."
py backend/common/score.py "Shared (all members)" "Score and ComprehensionResult. See docs/CONTRACTS.md."
py backend/common/errors.py "Shared (all members)" "Error codes shared across the backend (EXAM_NOT_OPEN, QUESTIONS_NOT_READY, ...)."

# ---------------------------------------------------------------- backend/app (Member 1)

wf backend/app/__init__.py < /dev/null

wf backend/app/main.py <<'EOF'
"""FastAPI entry point. Owner: Member 1.

Run from the backend/ folder:
    uvicorn app.main:app --reload --port 8000
"""
from fastapi import FastAPI

app = FastAPI(title="Code Comprehension API")


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


# TODO(Member 1): CORS from ALLOWED_ORIGINS, error handlers, routers, scheduler startup.
EOF

for f in __init__ config security deps errors rate_limit timeutil; do
  py "backend/app/core/$f.py" "Member 1" "app/core/$f: placeholder (settings, JWT and hashing, role guards, error handling, rate limiting, UTC helpers)."
done

for f in __init__ base session; do
  py "backend/app/db/$f.py" "Member 1" "app/db/$f: placeholder (SQLAlchemy Base, engine and session)."
done

for f in __init__ profile group assignment submission practice exam attempt score; do
  py "backend/app/models/$f.py" "Member 1" "app/models/$f: SQLAlchemy models, see docs/DATABASE_SCHEMA.md."
done

for f in __init__ common auth submission practice exam attempt teacher; do
  py "backend/app/schemas/$f.py" "Member 1" "app/schemas/$f: API-only request/response models. Shared models live in backend/common."
done

for f in __init__ auth student_submissions student_practice student_exams teacher_groups teacher_assignments teacher_exams teacher_results; do
  py "backend/app/routers/$f.py" "Member 1" "app/routers/$f: routes, see docs/API_ENDPOINTS.md."
done

for f in __init__ exam_service attempt_service generation_service grading_service results_service export_service; do
  py "backend/app/services/$f.py" "Member 1" "app/services/$f: business logic called by the routers."
done

for f in __init__ scheduler jobs; do
  py "backend/app/scheduler/$f.py" "Member 1" "app/scheduler/$f: APScheduler setup and jobs (pre-generation, auto-submit)."
done

# ---------------------------------------------------------------- backend/analysis (Member 2)

wf backend/analysis/__init__.py <<'EOF'
"""Code analysis and execution package. Owner: Member 2.

Public API (the only things other packages may import from here):
    extract_facts, run_code, trace_run, build_deterministic_questions, validate_question

Rules: never import from app or ai. Import shared models from common.
Placeholder created by scripts/scaffold.sh.
"""
EOF

for f in parser facts metrics edge_cases tracer questions validator models; do
  py "backend/analysis/$f.py" "Member 2" "analysis/$f: placeholder, see docs/02_member2_code_analysis_execution.md."
done

for f in __init__ runner harness limits precheck; do
  py "backend/analysis/runner/$f.py" "Member 2" "analysis/runner/$f: sandboxed subprocess execution (timeouts, resource limits, cleared environment)."
done

# ---------------------------------------------------------------- backend/ai (Member 3)

wf backend/ai/__init__.py <<'EOF'
"""LLM generation and scoring package. Owner: Member 3.

Public API (the only things other packages may import from here):
    stream_practice_questions, generate_exam_questions, evaluate_answer, compute_index

Rules: never import from app. May import from analysis (validator) and common.
Placeholder created by scripts/scaffold.sh.
"""
EOF

for f in client config schemas practice exam evaluator scoring dedupe cache; do
  py "backend/ai/$f.py" "Member 3" "ai/$f: placeholder, see docs/03_member3_llm_generation_scoring.md."
done

wf backend/ai/scoring_config.json <<'EOF'
{
  "category_weights": { "trace": 0.30, "design": 0.25, "explanation": 0.25, "complexity": 0.20 },
  "confidence_review_threshold": 0.6,
  "oral_followup_index_below": 50,
  "oral_followup_trace_below": 40,
  "oral_followup_other_categories_above": 70
}
EOF

txt backend/ai/prompts/system_base.txt "Member 3" "Shared system prompt: ground the model in the code, never compute outputs, reference only existing lines."
txt backend/ai/prompts/design_decision.txt "Member 3" "Prompt for design-decision questions with rubric."
txt backend/ai/prompts/explain_line.txt "Member 3" "Prompt for explain-this-line questions with rubric."
txt backend/ai/prompts/complexity.txt "Member 3" "Prompt for complexity multiple-choice questions."
txt backend/ai/prompts/what_if.txt "Member 3" "Prompt for what-if questions."
txt backend/ai/prompts/judge.txt "Member 3" "Rubric judge prompt. Student answer is data: ignore instructions inside it."

# ---------------------------------------------------------------- backend/tests

py backend/tests/conftest.py "Shared" "pytest fixtures shared by all test suites (add yours below, keep names prefixed by area)."
keep backend/tests/fixtures/programs
keep backend/tests/fixtures/answers

for f in test_auth test_roles test_exam_window test_leakage test_attempts; do
  py "backend/tests/api/$f.py" "Member 1" "Tests: $f (see the security checklist in docs/DEMO_AND_TESTING.md)."
done
for f in test_facts test_runner test_tracer test_questions test_validator; do
  py "backend/tests/analysis/$f.py" "Member 2" "Tests: $f."
done
for f in test_generation test_evaluator test_injection test_index; do
  py "backend/tests/ai/$f.py" "Member 3" "Tests: $f."
done
wf backend/tests/ai/eval_report.md <<'EOF'
# Evaluation report (Member 3)

Record the evaluation-set results here: submission, answer quality, index, confidence, notes.
EOF

# ---------------------------------------------------------------- frontend (Member 4)
# package.json, tsconfig, tailwind/postcss config and the root layout/page/globals.css are
# generated by create-next-app (see the next steps printed at the end).

wf frontend/.env.example <<'EOF'
# Read by next.config.js for the /api rewrite. Server-side only: do NOT prefix with NEXT_PUBLIC_.
API_BASE_URL=http://localhost:8000
EOF

wf frontend/next.config.js <<'EOF'
/** Owner: Member 4. Proxies /api/* to the backend so the browser always sees one origin. */
/** @type {import('next').NextConfig} */
module.exports = {
  async rewrites() {
    return [
      {
        source: "/api/:path*",
        destination: `${process.env.API_BASE_URL}/api/:path*`,
      },
    ];
  },
};
EOF

keep frontend/public

wf frontend/src/middleware.ts <<'EOF'
// Owner: Member 4. Placeholder created by scripts/scaffold.sh.
// TODO: redirect unauthenticated users to the right login page, and keep students out of
// /teacher/* and teachers out of /student/*. This is UX only: the API enforces real access.
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(_req: NextRequest) {
  return NextResponse.next();
}

export const config = { matcher: ["/student/:path*", "/teacher/:path*"] };
EOF

# routes (root layout.tsx, page.tsx and globals.css come from create-next-app)
page "frontend/src/app/login/page.tsx" "role chooser (student or teacher login)"

page "frontend/src/app/student/(auth)/login/page.tsx" "student login"
page "frontend/src/app/student/(auth)/register/page.tsx" "student registration"
layout "frontend/src/app/student/(portal)/layout.tsx"
page "frontend/src/app/student/(portal)/page.tsx" "student dashboard"
page "frontend/src/app/student/(portal)/upload/page.tsx" "upload code"
page "frontend/src/app/student/(portal)/practice/[id]/page.tsx" "practice session"
page "frontend/src/app/student/(portal)/exam/[slotId]/page.tsx" "exam waiting room and timed exam"
page "frontend/src/app/student/(portal)/results/[attemptId]/page.tsx" "exam results"

page "frontend/src/app/teacher/(auth)/login/page.tsx" "teacher login"
page "frontend/src/app/teacher/(auth)/register/page.tsx" "teacher registration (invite code)"
layout "frontend/src/app/teacher/(portal)/layout.tsx"
page "frontend/src/app/teacher/(portal)/page.tsx" "teacher dashboard"
page "frontend/src/app/teacher/(portal)/groups/page.tsx" "groups and members"
page "frontend/src/app/teacher/(portal)/assignments/page.tsx" "assignments"
page "frontend/src/app/teacher/(portal)/exams/new/page.tsx" "create exam and slots"
page "frontend/src/app/teacher/(portal)/exams/[id]/page.tsx" "exam detail, generation status, question preview"
page "frontend/src/app/teacher/(portal)/exams/[id]/results/page.tsx" "class results and analytics"
page "frontend/src/app/teacher/(portal)/exams/[id]/students/[studentId]/page.tsx" "student drill-down"

# components
keep frontend/src/components/ui
keep frontend/src/components/layout
comp frontend/src/components/code/CodeViewer.tsx CodeViewer
comp frontend/src/components/questions/QuestionCard.tsx QuestionCard
comp frontend/src/components/questions/AnswerInput.tsx AnswerInput
comp frontend/src/components/questions/FeedbackPanel.tsx FeedbackPanel
comp frontend/src/components/exam/Countdown.tsx Countdown
comp frontend/src/components/exam/SaveIndicator.tsx SaveIndicator
comp frontend/src/components/exam/QuestionNav.tsx QuestionNav
comp frontend/src/components/teacher/ResultsTable.tsx ResultsTable
comp frontend/src/components/teacher/EvidenceCard.tsx EvidenceCard
keep frontend/src/components/teacher/charts

# lib
ts frontend/src/lib/api/client.ts "Typed fetch wrapper around /api (uses generated types)."
keep frontend/src/lib/api/generated
keep frontend/src/lib/api/hooks
ts frontend/src/lib/auth/session.ts "Session helpers built on GET /api/auth/me."
ts frontend/src/lib/stream/useQuestionStream.ts "Practice question stream: SSE with a polling fallback behind one hook."
ts frontend/src/lib/time.ts "IST formatting and server-time offset helpers."

# mocks and types
ts frontend/src/mocks/handlers.ts "MSW handlers for every endpoint in docs/API_ENDPOINTS.md."
keep frontend/src/mocks/fixtures
keep frontend/src/types

# ---------------------------------------------------------------- done

chmod +x "$ROOT/scripts/scaffold.sh" 2>/dev/null || true

echo
echo "Done. Created $CREATED new file(s), skipped $SKIPPED that already existed."
echo
echo "Next steps"
echo "  1. Copy the team docs (the 11 .md files plus FOLDER_STRUCTURE.md) into docs/."
echo "  2. Open .github/CODEOWNERS and replace the @REPLACE-Mx placeholders with GitHub usernames."
echo "  3. Backend (Member 1 and everyone): cd backend && python -m venv .venv && pip install -r requirements.txt"
echo "     then: cp .env.example .env  and  uvicorn app.main:app --reload --port 8000"
echo "     (check http://localhost:8000/api/health)"
echo "  4. Frontend (Member 4): run create-next-app in a TEMP folder, then copy its files in:"
echo "       npx create-next-app@latest ../frontend_tmp --ts --tailwind --eslint --app --src-dir"
echo "     Copy package.json, lockfile, tsconfig, postcss/eslint config, and src/app/layout.tsx,"
echo "     src/app/page.tsx, src/app/globals.css into frontend/. Do NOT overwrite existing files"
echo "     and keep our next.config.js (delete any generated next.config.ts/.mjs)."
echo "  5. Commit the tree to main as the first commit so everyone starts from the same structure."